### ISSUE TITLE
Issue with sha256 circuit benchmark

### ISSUE THREAD

**Issue by vivijj** [matter-labs/era-boojum#5]
Hello zkSync Team,

I am currently conducting research using the era-boojum proof system and have encountered an issue during the execution of the SHA-256 benchmark, the program appears to stall at the CSReferenceAssembly::wait_for_witness() function, both run_sha256_prover_non_recursive and run_sha256_prover_recursive_mode_poseidon2.

**Comment by arose0** [comment]
Hey @vivijj - can you share what steps you took here so that we can investigate?

**Comment by vivijj** [comment]
I ran the following script on a Mac Pro M1 with 16GB of RAM:
`RUSTFLAGS='-C target-cpu=native' cargo +nightly test --release -- --nocapture run_sha256_prover_non_recursive --ignored`
By default, the test preimage size is set to 8KB, which causes the proving process to get stuck. I have tried changing the preimage size to 4KB and 2KB, and only when it is set to 2KB does the process not get stuck.

**Comment by canaancc** [comment]
I have the same problem

**Comment by canaancc** [comment]
Hi，when this issue can be solved, when the internal repo can be published?

**Comment by shamatar** [comment]
I believe it was updated

**Comment by vivijj** [comment]
Seems alright. By the way, when do you plan to open source your GPU prover for Boojum? @shamatar

**Comment by arose0** [comment]
@
