### ISSUE TITLE
Copyright violation by boojum of plonky2

### ISSUE THREAD

**Issue by paulmillr** [matter-labs/era-boojum#7]
Boojum violates terms of MIT / Apache license.

This line says you've used plonky2 source code:

https://github.com/matter-labs/era-boojum/blob/8b4955f1c24d4d35db7e4ed79aa9b107260ebc8c/src/field/goldilocks/mod.rs#L1

But it is not enough. You must include their copyright, even if it's just 5% of code reuse.

**Comment by arose0** [comment]
Thanks for opening the issue @paulmillr - see this PR to address this: https://github.com/matter-labs/era-boojum/pull/8

**Comment by arose0** [comment]
This issue has been addressed in https://github.com/matter-labs/era-boojum/pull/8
